module.exports = (app) => {
  const { router, controller, middleware } = app;
  router.get(
    "/storeMsMini/index",
    middleware.jwt("mini"),
    controller.storeMsMini.user.index
  );
  router.get(
    "/storeMsMini/checkUserLogin",
    middleware.jwt("mini"),
    controller.storeMsMini.user.checkUserLogin
  );
  router.post(
    "/storeMsMini/registerUser",
    middleware.jwt("mini"),
    controller.storeMsMini.user.registerUser
  );
  router.get(
    "/storeMsMini/getUser",
    middleware.jwt("mini"),
    controller.storeMsMini.user.getUser
  );
  router.get(
    "/storeMsMini/getMineData",
    middleware.jwt("mini"),
    controller.storeMsMini.user.getMineData
  );
  router.get(
    "/storeMsMini/getBalanceUser",
    middleware.jwt("mini"),
    controller.storeMsMini.user.getBalanceUser
  );
  router.post(
    "/storeMsMini/payCharge",
    middleware.jwt("mini"),
    controller.storeMsMini.user.payCharge
  );
  router.post(
    "/storeMsMini/reCharge",
    middleware.jwt("mini"),
    controller.storeMsMini.user.reCharge
  );
  router.get(
    "/storeMsMini/getMyPurchaseRecordList",
    middleware.jwt("mini"),
    controller.storeMsMini.user.getMyPurchaseRecordList
  );
  router.get(
    "/storeMsMini/getFilterDramaList",
    middleware.jwt("mini"),
    controller.storeMsMini.drama.getFilterDramaList
  );
  router.get(
    "/storeMsMini/getDramaDetail",
    middleware.jwt("mini"),
    controller.storeMsMini.drama.getDramaDetail
  );
  router.get(
    "/storeMsMini/getHomeDramas",
    middleware.jwt("mini"),
    controller.storeMsMini.drama.getHomeDramas
  );
  router.post(
    "/storeMsMini/collectDrama",
    middleware.jwt("mini"),
    controller.storeMsMini.drama.collectDrama
  );
  router.post(
    "/storeMsMini/unCollectDrama",
    middleware.jwt("mini"),
    controller.storeMsMini.drama.unCollectDrama
  );
  router.get(
    "/storeMsMini/getMyCollectDramaList",
    middleware.jwt("mini"),
    controller.storeMsMini.drama.getMyCollectDramaList
  );
  router.get(
    "/storeMsMini/getTeamList",
    middleware.jwt("mini"),
    controller.storeMsMini.team.getTeamList
  );
  router.get(
    "/storeMsMini/getMyTeamList",
    middleware.jwt("mini"),
    controller.storeMsMini.team.getMyTeamList
  );
  router.get(
    "/storeMsMini/getTeamDetail",
    middleware.jwt("mini"),
    controller.storeMsMini.team.getTeamDetail
  );
  router.post(
    "/storeMsMini/joinTeam",
    middleware.jwt("mini"),
    controller.storeMsMini.team.joinTeam
  );
  router.post(
    "/storeMsMini/quitTeam",
    middleware.jwt("mini"),
    controller.storeMsMini.team.quitTeam
  );
  router.get(
    "/storeMsMini/getRooms",
    middleware.jwt("mini"),
    controller.storeMsMini.store.getRooms
  );
  router.get(
    "/storeMsMini/getDms",
    middleware.jwt("mini"),
    controller.storeMsMini.store.getDms
  );
  router.get(
    "/storeMsMini/getGoods",
    middleware.jwt("mini"),
    controller.storeMsMini.store.getGoods
  );
  router.post(
    "/storeMsMini/placeOrder",
    middleware.jwt("mini"),
    controller.storeMsMini.store.placeOrder
  );
  router.get(
    "/storeMsMini/getMyOrderList",
    middleware.jwt("mini"),
    controller.storeMsMini.store.getMyOrderList
  );
  router.get(
    "/storeMsMini/getOrderDetail",
    middleware.jwt("mini"),
    controller.storeMsMini.store.getOrderDetail
  );
  router.post(
    "/storeMsMini/updaTeOrder",
    middleware.jwt("mini"),
    controller.storeMsMini.store.updaTeOrder
  );
};
